wallpaper {
    monitor = DP-3
    path = ~/wallpapers/bandori/1.png
    # fit_mode = contain
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1
    path = ~/wallpapers/bandori/2.png
    # fit_mode = contain
    fit_mode = cover
}

wallpaper {
    monitor = DP-1
    path = ~/wallpapers/bandori/3.png
    # fit_mode = contain
    fit_mode = cover
}
