
# https://wiki.hyprland.org/Configuring/Monitors/

$monitor1 = DP-3
$monitor2 = HDMI-A-1
$monitor3 = DP-1

monitorv2 {
    output = $monitor1
    mode = 1920x1080@180
    position = 0x0
    scale = 1
    bitdepth = 10
    cm = hdr
    supports_wide_color = 1
    supports_hdr = 1
    sdrbrightness = 1.25
    sdrsaturation = 1.05
    sdr_min_luminance = 0.005
    sdr_max_luminance = 75
}
monitorv2 {
    output = $monitor2
    mode = 1920x1080@60
    position = -1080x-330 # -1080x-420 is centered, but it's a bit different to match physical monitor
    scale = 1
    transform = 1
}
monitorv2 {
    output = $monitor3
    mode = 1920x1080@60
    position = 1920x0
    scale = 1
}

# https://wiki.hyprland.org/Configuring/Variables/#misc
misc {
    vrr = 2 # Variable Refresh Rate (Adaptive Sync) # 2 = only fulsscreen
    render_unfocused_fps = 15 # default 15 # does this mean 2nd window videos are capped ?? maybe add some exceptions in window rules, check variable descrip
}

render {
    # HDR options
    # cm_fs_passthrough = 1 # Passthrough color settings for fullscreen apps when possible. 0 - off, 1 - always, 2 - hdr only

    # this causes severe visual glitches (parts of the screen going black), especially on fullscreened xwayland apps with popups
    # direct_scanout = 1 # apparently can improve latency for fullscreen windows, but sometimes cause glitches, so if it happens, disable it
    # this also apparently requires fullscreen apps to support hdr when it's on or they look over-saturated
}

quirks {
    prefer_hdr = 1
}
