
# Assign workspaces per monitor
workspace = 1,  monitor:$monitor1,                   default:true
workspace = 2,  monitor:$monitor2, layout:scrolling, default:true
workspace = 3,  monitor:$monitor3,                   default:true
workspace = 4,  monitor:$monitor1,
workspace = 5,  monitor:$monitor2, layout:scrolling
workspace = 6,  monitor:$monitor3,
workspace = 7,  monitor:$monitor1,
workspace = 8,  monitor:$monitor2, layout:scrolling
workspace = 9,  monitor:$monitor3,
workspace = 10, monitor:$monitor1,
workspace = 11, monitor:$monitor2, layout:scrolling
workspace = 12, monitor:$monitor3,

# make special workspaces 3x the gaps as normal workspaces
workspace = special:1, gapsin:12, gapsout:36
workspace = special:2, gapsin:12, gapsout:36
workspace = special:3, gapsin:12, gapsout:36
workspace = special:4, gapsin:12, gapsout:36



# Monitor-specific layout options, like direction/orientation

# Monitor 1
# Master
workspace = m[$monitor1]w[tv1], layoutopt:orientation:center
workspace = m[$monitor1]w[tv2-6], layoutopt:orientation:right
workspace = m[$monitor1]w[tv7-999999], layoutopt:orientation:center
# Scrolling
workspace = m[$monitor1], layoutopt:direction:right

# Monitor 2
# Master
# master layout has some issues with vertical monitors, check new versions for fixes
# this could be a workaround IF IT WORKED
# workspace = m[$monitor2], layoutopt:always_keep_position:false
workspace = m[$monitor2]w[tv1], layoutopt:orientation:right # center
workspace = m[$monitor2]w[tv2-4], layoutopt:orientation:bottom
workspace = m[$monitor2]w[tv5-999999], layoutopt:orientation:bottom # center
# Scrolling
workspace = m[$monitor2], layoutopt:direction:down

# Monitor 3
# Master
workspace = m[$monitor3]w[tv1-6], layoutopt:orientation:left
workspace = m[$monitor3]w[tv7-999999], layoutopt:orientation:center
# Scrolling
workspace = m[$monitor3], layoutopt:direction:left
