
# https://wiki.hyprland.org/Configuring/Monitors/


$monitor1 = DP-3
$monitor2 = HDMI-A-1
$monitor3 = DP-1

monitorv2 {
    output = $monitor1
    mode = 1920x1080@180
    position = 0x0
    scale = 1
    bitdepth = 10
    cm = hdr
    supports_wide_color = 1
    supports_hdr = 1
    sdrbrightness = 1.25
    sdrsaturation = 1.05
    sdr_min_luminance = 0.005
    sdr_max_luminance = 75
}

# Using only 1 monitor saves a lot of GPU memory
monitor = $monitor2, disable
monitor = $monitor3, disable

# https://wiki.hyprland.org/Configuring/Variables/#misc
misc {
    vrr = 1 # Variable Refresh Rate (Adaptive Sync) # 2 = only fulsscreen
    render_unfocused_fps = 1 # default 15
}

render {
    # HDR options
    # cm_fs_passthrough = 1 # Passthrough color settings for fullscreen apps when possible. 0 - off, 1 - always, 2 - hdr only

    # this causes severe visual glitches (parts of the screen going black), especially on fullscreened xwayland apps with popups
    # direct_scanout = 1 # apparently can improve latency for fullscreen windows, but sometimes cause glitches, so if it happens, disable it
    # this also apparently requires fullscreen apps to support hdr when it's on or they look over-saturated
}


quirks {
    prefer_hdr = 1
}
